// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8ZUw3NB49_t1qcuFSseb5cNHJXbBKgI',
    appId: '1:836986963698:web:ce7c64737d113e3006726b',
    messagingSenderId: '836986963698',
    projectId: 'login-flight-airplane',
    authDomain: 'login-flight-airplane.firebaseapp.com',
    storageBucket: 'login-flight-airplane.appspot.com',
    measurementId: 'G-JJV6J1GYW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGvITsbLOv_WiKUxb156MDhf1DaoDej0',
    appId: '1:836986963698:android:e3bcd650716b8e1206726b',
    messagingSenderId: '836986963698',
    projectId: 'login-flight-airplane',
    storageBucket: 'login-flight-airplane.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZTkTUbxN5_tyuDMWherrdeg1dFqL_pc',
    appId: '1:836986963698:ios:8fb3f9fca3e5b6a606726b',
    messagingSenderId: '836986963698',
    projectId: 'login-flight-airplane',
    storageBucket: 'login-flight-airplane.appspot.com',
    iosBundleId: 'com.example.flightAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPZTkTUbxN5_tyuDMWherrdeg1dFqL_pc',
    appId: '1:836986963698:ios:8fb3f9fca3e5b6a606726b',
    messagingSenderId: '836986963698',
    projectId: 'login-flight-airplane',
    storageBucket: 'login-flight-airplane.appspot.com',
    iosBundleId: 'com.example.flightAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf8ZUw3NB49_t1qcuFSseb5cNHJXbBKgI',
    appId: '1:836986963698:web:71e427d70a61992006726b',
    messagingSenderId: '836986963698',
    projectId: 'login-flight-airplane',
    authDomain: 'login-flight-airplane.firebaseapp.com',
    storageBucket: 'login-flight-airplane.appspot.com',
    measurementId: 'G-6CLJ3T59MK',
  );
}
